name: CI Pipeline - TourGuide

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest # Runner Windows car tu développes sur Windows

    steps:
      # 1. Récupérer le code source du dépôt
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Installer Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache des dépendances Maven pour accélérer les builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Compiler le projet et exécuter les tests
      - name: Build and run tests
        run: mvn clean install --batch-mode

      # 5. Sauvegarder le JAR généré en tant qu'artefact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: tourguide-jar
          path: TourGuide/target/*.jar
