name: Java Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test (Windows)
    runs-on: windows-latest

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuration du JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Compilation et tests
      - name: Build with Maven
        run: .\mvnw.cmd clean verify

  run-app:
    name: Run Application (Windows)
    runs-on: windows-latest
    needs: build

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuration du JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Démarrage de l'application
      - name: Start Spring Boot App
        run: |
          Start-Process -FilePath ".\mvnw.cmd" -ArgumentList "spring-boot:run" -NoNewWindow
          Start-Sleep -Seconds 20
          curl http://localhost:8080
